services:
  docs:
    build:
      context: ..
      dockerfile: Dockerfile
    ports:
      - "12000:4321"
      - "12001:8081"
      - "12002:8082"
      - "12003:8083"
    environment:
      - SPEC_EXTERNAL_PORT=12001
    volumes:
      - ./docs:/app/starlight/src/content/docs
      - ./openapi:/app/api-design
      - ./astro.config.mjs:/app/starlight/astro.config.mjs
